export type ICSSPropValue = <T>(v: string, o: T) => string
export type ICSSSimplePropValue = <T>(v: T) => string | undefined

export default interface ICCSSProps {
    a?: ICSSPropValue
    ad?: ICSSPropValue
    aDir?: ICSSPropValue
    aD?: ICSSPropValue
    afm?: ICSSPropValue
    aic?: ICSSPropValue
    an?: ICSSPropValue
    aps?: ICSSPropValue
    ats?: ICSSPropValue
    bv?: ICSSPropValue
    per?: ICSSPropValue
    pero?: ICSSPropValue
    tf?: ICSSPropValue
    tfo?: ICSSPropValue
    tfs?: ICSSPropValue
    tr?: ICSSPropValue
    trD?: ICSSPropValue
    trd?: ICSSPropValue
    trp?: ICSSPropValue
    trt?: ICSSPropValue
    fd?: ICSSPropValue
    fw?: ICSSPropValue
    fb?: ICSSPropValue
    ff?: ICSSPropValue
    fg?: ICSSPropValue
    fs?: ICSSPropValue
    ai?: ICSSPropValue
    ac?: ICSSPropValue
    ji?: ICSSPropValue
    jc?: ICSSPropValue
    aS?: ICSSPropValue
    jS?: ICSSPropValue
    ft?: ICSSPropValue
    ftf?: ICSSPropValue
    ftk?: ICSSPropValue
    fts?: ICSSPropValue
    ftStretch?: ICSSPropValue
    ftStyle?: ICSSPropValue
    ftv?: ICSSPropValue
    ftw?: ICSSPropValue
    ls?: ICSSPropValue
    lh?: ICSSPropValue
    ta?: ICSSPropValue
    td?: ICSSPropValue
    ti?: ICSSPropValue
    to?: ICSSPropValue
    ts?: ICSSPropValue
    tt?: ICSSPropValue
    va?: ICSSPropValue
    ws?: ICSSPropValue
    wb?: ICSSPropValue
    wS?: ICSSPropValue
    ww?: ICSSPropValue
    listS?: ICSSPropValue
    listSI?: ICSSPropValue
    listSP?: ICSSPropValue
    listST?: ICSSPropValue
    /** margin */
    m?: ICSSPropValue
    /** margin-top */
    mt?: ICSSPropValue
    mr?: ICSSPropValue
    /** margin-bottom */
    mb?: ICSSPropValue
    /** margin-left */
    ml?: ICSSPropValue
    p?: ICSSPropValue
    pt?: ICSSPropValue
    pr?: ICSSPropValue
    pb?: ICSSPropValue
    pl?: ICSSPropValue
    bg?: ICSSPropValue
    bgi?: ICSSPropValue
    bgc?: ICSSPropValue
    bgs?: ICSSPropValue
    bgr?: ICSSPropValue
    bgp?: ICSSPropValue
    bga?: ICSSPropValue
    bgbm?: ICSSPropValue
    bgC?: ICSSPropValue
    bgo?: ICSSPropValue
    w?: ICSSPropValue
    h?: ICSSPropValue
    minW?: ICSSPropValue
    minH?: ICSSPropValue
    maxW?: ICSSPropValue
    maxH?: ICSSPropValue
    g?: ICSSPropValue
    ga?: ICSSPropValue
    gac?: ICSSPropValue
    gaf?: ICSSPropValue
    gar?: ICSSPropValue
    gc?: ICSSPropValue
    gce?: ICSSPropValue
    gcg?: ICSSPropValue
    gcs?: ICSSPropValue
    gg?: ICSSPropValue
    gr?: ICSSPropValue
    gre?: ICSSPropValue
    grg?: ICSSPropValue
    grs?: ICSSPropValue
    gt?: ICSSPropValue
    gta?: ICSSPropValue
    gtc?: ICSSPropValue
    gtr?: ICSSPropValue
    b?: ICSSPropValue
    bb?: ICSSPropValue
    bbc?: ICSSPropValue
    bblr?: ICSSPropValue
    bbrr?: ICSSPropValue
    bbs?: ICSSPropValue
    bbw?: ICSSPropValue
    bC?: ICSSPropValue
    bc?: ICSSPropValue
    bi?: ICSSPropValue
    bio?: ICSSPropValue
    bir?: ICSSPropValue
    bis?: ICSSPropValue
    biSrc?: ICSSPropValue
    biw?: ICSSPropValue
    bl?: ICSSPropValue
    blc?: ICSSPropValue
    bls?: ICSSPropValue
    blw?: ICSSPropValue
    r?: ICSSPropValue
    br?: ICSSPropValue
    brc?: ICSSPropValue
    brs?: ICSSPropValue
    brw?: ICSSPropValue
    bs?: ICSSPropValue
    bS?: ICSSPropValue
    bt?: ICSSPropValue
    btc?: ICSSPropValue
    btlr?: ICSSPropValue
    btrr?: ICSSPropValue
    bts?: ICSSPropValue
    btw?: ICSSPropValue
    bw?: ICSSPropValue
    clip?: ICSSPropValue
    clipPath?: ICSSPropValue
    d?: ICSSPropValue
    pos?: ICSSPropValue
    T?: ICSSPropValue
    R?: ICSSPropValue
    B?: ICSSPropValue
    L?: ICSSPropValue
    z?: ICSSPropValue
    c?: ICSSPropValue
    o?: ICSSPropValue
    ox?: ICSSPropValue
    oy?: ICSSPropValue
    fl?: ICSSPropValue
    clr?: ICSSPropValue
    v?: ICSSPropValue
    col?: ICSSPropValue
    cc?: ICSSPropValue
    cf?: ICSSPropValue
    cg?: ICSSPropValue
    cr?: ICSSPropValue
    crc?: ICSSPropValue
    crs?: ICSSPropValue
    crw?: ICSSPropValue
    cs?: ICSSPropValue
    cw?: ICSSPropValue
    pba?: ICSSPropValue
    pbb?: ICSSPropValue
    pbi?: ICSSPropValue
    shadow?: ICSSPropValue
    sizing?: ICSSPropValue
    of?: ICSSPropValue
    oP?: ICSSPropValue
    op?: ICSSPropValue
    or?: ICSSPropValue
    ol?: ICSSPropValue
    mbm?: ICSSPropValue
    ct?: ICSSPropValue
    cur?: ICSSPropValue
    pe?: ICSSPropValue
    fil?: ICSSPropValue
    sb?: ICSSPropValue
    us?: ICSSPropValue
    styleText?: ICSSPropValue
    mid?: ICSSPropValue
    hScroll?: ICSSPropValue
    ps?: ICSSSimplePropValue
    mq?: ICSSSimplePropValue
    theme?: ICSSPropValue
}
